spring:
  application:
    name: edo-spike
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spike?useUnicode=true&characterEncoding=utf-8
    username: spike
    password: spike

server:
  port: 8080

mybatis:
  type-aliases-package: org.framework.edo.spike.model
  mapperLocations: classpath:daoXml/*.xml
