spring:
  application:
    name: edo-spike
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spike?useUnicode=true&characterEncoding=utf-8
    username: spike
    password: spike

server:
  port: 8080

mybatis:
  type-aliases-package: org.framework.edo.spike.model
  mapperLocations: classpath:daoXml/*.xml

# 注释 1.字符串可以不加引号
person:
  id: 1
  name: lucy
  hobby: [吃饭,睡觉,打豆豆]
  family: [father,mother]
  map: {k1: v1,k2: v2}
  pet: {type: dog,name: 旺财}



